services:
  - type: web
    name: nagpur-flood-safe-backend
    env: python
    region: singapore
    plan: free
    buildCommand: cd BACKEND && pip install -r requirements.txt
    startCommand: cd BACKEND && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
